kind: pipeline
name : xCi
version: 2.1
steps:
 - name: xCi Console
   image: z4nyx/docker:latest
   environment:
     chat_id:
       from_secret: CHAT_ID
     token:
       from_secret: TOKEN
   commands:
       - apt update -y && apt upgrade -y
       - apt install -y python3-pip build-essential libssl-dev libffi-dev python3-dev
       - git config --global user.name "xyzuan"
       - git config --global user.email "xyzuan@webmail.umm.ac.id"
       - bash xdroid_lavender.sh
