kind: pipeline
name : xCi
version: 2.1
steps:
 - name: xCi Console
   image: z4nyx/docker:latest
   environment:
     ZIP_RELEASE:
       from_secret: ZIP_RELEASE
     TOKEN:
       from_secret: BOT_API_KEY
     CHATID:
       from_secret: CHAT_ID
     ZIPNAME:
       from_secret: ZIPNAME
   commands: |
       apt update -y && apt upgrade -y
       git config --global user.name "xyzuan"
       git config --global user.email "xyzuan@webmail.umm.ac.id"
       git clone --depth=1 https://github.com/xyz-prjkt/xbore_strmbreakr_lavender lavender
       wget https://github.com/xyz-prjkt/xbore_strmbreakr_lavender/raw/eleven-caf_eas/.circleci/build.sh
       bash build.sh
