kind: pipeline
name : xDroidBuilder
version: 2.1
steps:
 - name: test
   image: starlight2834/ci_docker:latest
   environment:
     ZIP_RELEASE:
       from_secret: ZIP_RELEASE
     TOKEN:
       from_secret: BOT_API_KEY
     CHATID:
       from_secret: CHAT_ID
     ZIPNAME:
       from_secret: ZIPNAME
   commands:
      - apt update -y && apt upgrade -y && apt install neofetch -y && neofetch && df -l
