version: 2.1
jobs:
  compile:
   docker:
      - image: xyzuan/xdocker:latest
   steps:
      - run:
          command: |
           bash .circleci/compile.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
