version: 2.1
jobs:
  compile:
   docker:
      - image: xyzuan/xdocker:latest
   steps:
      - run:
          command: |
           git config --global user.name "fazrul1994"
           git config --global user.email "fazrulfadhilah@gmail.com"
           git clone https://github.com/fazrul1994/xDroneCi circle
           cd circle
           bash .circleci/compile.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
