version: 2.1
jobs:
  compile:
   docker:
      - image: xyzuan/xdocker:latest
   steps:
      - run:
          command: |
           apt install neofetch -y
           neofetch
           git config --global user.name "fazrul1994"
           git config --global user.email "fazrulfadhilah@gmail.com"
           apt update -y && apt upgrade -y
           git config --global user.name "fazrul1994"
           git config --global user.email "fazrulfadhilah@gmail.com"
           git clone --depth=1 https://github.com/fazrul1994/android_kernel_sony_msm8998 poplar
           bash xbore_lavender.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
